In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np

In [2]:
grid = np.arange(13)
a, b = np.meshgrid(grid, grid)

In [3]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [4]:
torch.FloatTensor(a).view(-1, 1)

tensor([[ 0.],
        [ 1.],
        [ 2.],
        [ 3.],
        [ 4.],
        [ 5.],
        [ 6.],
        [ 7.],
        [ 8.],
        [ 9.],
        [10.],
        [11.],
        [12.],
        [ 0.],
        [ 1.],
        [ 2.],
        [ 3.],
        [ 4.],
        [ 5.],
        [ 6.],
        [ 7.],
        [ 8.],
        [ 9.],
        [10.],
        [11.],
        [12.],
        [ 0.],
        [ 1.],
        [ 2.],
        [ 3.],
        [ 4.],
        [ 5.],
        [ 6.],
        [ 7.],
        [ 8.],
        [ 9.],
        [10.],
        [11.],
        [12.],
        [ 0.],
        [ 1.],
        [ 2.],
        [ 3.],
        [ 4.],
        [ 5.],
        [ 6.],
        [ 7.],
        [ 8.],
        [ 9.],
        [10.],
        [11.],
        [12.],
        [ 0.],
        [ 1.],
        [ 2.],
        [ 3.],
        [ 4.],
        [ 5.],
        [ 6.],
        [ 7.],
        [ 8.],
        [ 9.],
        [10.],
        [11.],
        [12.],
        [ 0.],
        [ 

In [5]:
b

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2],
       [ 3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3],
       [ 4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4],
       [ 5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5],
       [ 6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6],
       [ 7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7],
       [ 8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8],
       [ 9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11],
       [12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12]])

In [6]:
torch.FloatTensor(b).view(-1, 1)

tensor([[ 0.],
        [ 0.],
        [ 0.],
        [ 0.],
        [ 0.],
        [ 0.],
        [ 0.],
        [ 0.],
        [ 0.],
        [ 0.],
        [ 0.],
        [ 0.],
        [ 0.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 2.],
        [ 2.],
        [ 2.],
        [ 2.],
        [ 2.],
        [ 2.],
        [ 2.],
        [ 2.],
        [ 2.],
        [ 2.],
        [ 2.],
        [ 2.],
        [ 2.],
        [ 3.],
        [ 3.],
        [ 3.],
        [ 3.],
        [ 3.],
        [ 3.],
        [ 3.],
        [ 3.],
        [ 3.],
        [ 3.],
        [ 3.],
        [ 3.],
        [ 3.],
        [ 4.],
        [ 4.],
        [ 4.],
        [ 4.],
        [ 4.],
        [ 4.],
        [ 4.],
        [ 4.],
        [ 4.],
        [ 4.],
        [ 4.],
        [ 4.],
        [ 4.],
        [ 5.],
        [ 

In [2]:
anchors = [(10, 13), (16, 30), (33, 23)]
anchors = torch.FloatTensor(anchors)

In [7]:
anchors.repeat(5 * 5, 1).unsqueeze(0)

tensor([[[10., 13.],
         [16., 30.],
         [33., 23.],
         [10., 13.],
         [16., 30.],
         [33., 23.],
         [10., 13.],
         [16., 30.],
         [33., 23.],
         [10., 13.],
         [16., 30.],
         [33., 23.],
         [10., 13.],
         [16., 30.],
         [33., 23.],
         [10., 13.],
         [16., 30.],
         [33., 23.],
         [10., 13.],
         [16., 30.],
         [33., 23.],
         [10., 13.],
         [16., 30.],
         [33., 23.],
         [10., 13.],
         [16., 30.],
         [33., 23.],
         [10., 13.],
         [16., 30.],
         [33., 23.],
         [10., 13.],
         [16., 30.],
         [33., 23.],
         [10., 13.],
         [16., 30.],
         [33., 23.],
         [10., 13.],
         [16., 30.],
         [33., 23.],
         [10., 13.],
         [16., 30.],
         [33., 23.],
         [10., 13.],
         [16., 30.],
         [33., 23.],
         [10., 13.],
         [16., 30.],
         [33.

In [7]:
a = np.arange(16).reshape((4, 4))

In [13]:
ta = torch.from_numpy(a)

In [24]:
(ta > 5).float().unsqueeze(2).shape

torch.Size([4, 4, 1])

In [3]:
a = np.arange(25).reshape((5, 5))

In [8]:
a = np.array([1, 2, 2, 3, 4, 5, 4, 7, 6])

In [9]:
np.unique(a)

array([1, 2, 3, 4, 5, 6, 7])

In [14]:
torch.from_numpy(a).unsqueeze(0)

tensor([[1, 2, 2, 3, 4, 5, 4, 7, 6]])

In [15]:
torch.from_numpy(a).unsqueeze(1)

tensor([[1],
        [2],
        [2],
        [3],
        [4],
        [5],
        [4],
        [7],
        [6]])